// 在此处添加您的代码
namespace myfighter_dlc_dragon {

    function multishot (projectile2: Sprite, a: number, n: number, delay: number, offset: number, name: string) {
        if (n > 0) {
            fightext_skill.shoot2(fightext_projectile.projectileOwner(fightext_projectile.spriteToWave(projectile2)), name, fightext_projectile.projectileOwner(fightext_projectile.spriteToWave(projectile2)).x, fightext_projectile.projectileOwner(fightext_projectile.spriteToWave(projectile2)).y, a, 85, 10)
        }
        fightext_skill.after(delay, function () {
            multishot(projectile2, a + offset, n - 1, delay, offset, name)
        })
    }

    export function dragon_character() {
        // 在此处测试；当此软件包作为插件使用时，将不会编译此软件包。
        fightext_character.basicSet(img`
            ........................
            ........................
            ...........ccc..........
            ...........cccc.........
            .......ccc..ccccccc.....
            .......cccccc555555cc...
            ........ccb5555555555c..
            .....cc..b555555555555c.
            .....cccb555555ff155555c
            ......cb55555555ff55d55c
            ......b5555555555555555c
            ...cc.b555dd5555bb13bbc.
            ...cccd55ddddd555b3335c.
            .....bdddddddddd55b335c.
            ..cccdddddb55bbddd5555c.
            ..cccdddddb555bbbbcccc..
            ...ccddddddb5555cbcdc...
            ccccbdddddd5cb55cbcc....
            cddddddddd5555ccbbc.....
            .cddddddbdd555bbbcc.....
            ..ccdddbbbdd55cbcdc.....
            ....ccbbcbddddccdddcc...
            ......cccdd555dcccccc...
            ........cccccccc........
            `, "恶龙", function (player2) {
            fightext_character.setAtkImage(player2, fightext_character.atkimgKind.hand1, img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd5bbbb335c.
                ...ccbdddddddd5bbbb335c.
                .ccccddddddddd55bb3335c.
                cdcccdddddb55bb55b3335c.
                cddbddddddb555bb553335c.
                cddddddddddb5555b5555c..
                ccddddddbd55bb55cbccc...
                .ccddddbbbdd55ccbbc.....
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `, img`
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ....................................55..
                ..................................555...
                .................................555....
                ................................55......
                ...............................55.......
                ...............................5........
                ................................5...5...
                ..............................5.55555.55
                ..............................5555.5555.
                ...............................5.5...5..
                ........................................
                ...............................5........
                ...............................55.......
                ................................55......
                .................................555....
                ..................................555...
                ....................................55..
                `)
            fightext_character.setAtkImage(player2, fightext_character.atkimgKind.hand2, img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd5bbbb335c.
                ...ccbdddddddd5bbbb335c.
                .ccccddddddddd55bb3335c.
                cdcccdddddb55bb55b3335c.
                cddbddddddb555bb553335c.
                cddddddddddb5555b5555c..
                ccddddddbd55bb55cbccc...
                .ccddddbbbdd55ccbbc.....
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `, img`
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ....................................22..
                ..................................222...
                .................................222....
                ................................22......
                ...............................22.......
                ...............................2........
                ................................2...2...
                ..............................2.22222.22
                ..............................2222.2222.
                ...............................2.2...2..
                ........................................
                ...............................2........
                ...............................22.......
                ................................22......
                .................................222....
                ..................................222...
                ....................................22..
                `)
            fightext_character.setAtkImage(player2, fightext_character.atkimgKind.leg1, img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd5bbbb335c.
                ...ccbdddddddd5bbbb335c.
                .ccccddddddddd55bb3335c.
                cdcccdddddb55bb55b3335c.
                cddbddddddb555bb553335c.
                cddddddddddb5555b5555c..
                ccddddddbd55bb55cbccc...
                .ccddddbbbdd55ccbbc.....
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `, img`
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ....................................44..
                ..................................444...
                .................................444....
                ................................44......
                ...............................44.......
                ...............................4........
                ................................4...4...
                ..............................4.44444.44
                ..............................4444.4444.
                ...............................4.4...4..
                ........................................
                ...............................4........
                ...............................44.......
                ................................44......
                .................................444....
                ..................................444...
                ....................................44..
                `)
            fightext_character.setAtkImage(player2, fightext_character.atkimgKind.leg2, img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd5bbbb335c.
                ...ccbdddddddd5bbbb335c.
                .ccccddddddddd55bb3335c.
                cdcccdddddb55bb55b3335c.
                cddbddddddb555bb553335c.
                cddddddddddb5555b5555c..
                ccddddddbd55bb55cbccc...
                .ccddddbbbdd55ccbbc.....
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `, img`
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ........................................
                ....................................42..
                ..................................442...
                .................................422....
                ................................42......
                ...............................42.......
                ...............................2........
                ................................2...2...
                ..............................2.22222.24
                ..............................4242.4424.
                ...............................4.4...4..
                ........................................
                ...............................2........
                ...............................42.......
                ................................42......
                .................................442....
                ..................................442...
                ....................................42..
                `)
            fightext_character.setStImage(player2, fightext_character.stimgKind.Defence, img`
                ........ccc.............
                ........cccccccc........
                .....cc..cc55555cc......
                .....cccc555555555c.....
                .....ccb55555555555c....
                ...cc.b5555bcc555555c...
                ...ccb55555555c55d55c...
                ....cb5555dd55555555c...
                .....5555dd5555d5555c...
                ..cc.555dd555555dbbbc...
                ..ccc55ddd555555d555c...
                ...ccd5dbdd5555d555c....
                ....bdddb555bbbbbccc....
                ..cccdddb555cbbbbbbbc...
                ...ccddddb555cbbbbbbbc..
                ....cdddddb555cbbbbbbc..
                ...ccddddddb55cbbbbbbcc.
                ...cbddddd55bcbbbbbbbcc.
                ..cbdddddd5555bbbbbbbc..
                .cddddddbdd555bbbbbbc...
                cddddddbbbdd55cbbccc....
                ccccccbbcbddddccdddcc...
                ......cccdd555dcccccc...
                ........cccccccc........
                `)
            fightext_character.setStImage(player2, fightext_character.stimgKind.Hitover, img`
                ........ccc.............
                .......c555cccccccc.....
                ......c5555dbbbbbbccc...
                ......5555ddbbbbbdddbc..
                ....cc555d5ddbbbbddddbc.
                ...c5cccd555ddddddddddc.
                ..c55cbbbd55ddddddddcdc.
                ..ccccbcccdddddddddcccc.
                ....ccb555ccdddddddcc...
                ...cccb55555bbdddddcc...
                ..c555dbbb555bddddb.c...
                .c533b55ddddddd5ddc.....
                .c5333b555ddddd55dcc....
                .cbb31b5555ddd555bcc....
                c55555bb555555555b.c....
                c55d5555c5555555bc......
                c55555cc5555555bccc.....
                .c5555bcc55555b.ccc.....
                ..c5555555555bcc........
                ...cc555555ccccc........
                .....ccccccc.ccc........
                .........ccc............
                ..........cc............
                ........................
                `)
            fightext_character.setStImage(player2, fightext_character.stimgKind.Lie, img`
                ........................
                ................cccc....
                ................cddbc...
                .............cccccddbc..
                .........ccc..cccddddc..
                ......cc..cccbdddddddcc.
                ......cccbbddddddddddbc.
                ......ccb555dddddddbbbc.
                ...ccc.b55555ddddddbbbc.
                ...cccb5555ddddddddbbbc.
                ...ccb5555dddbbddddbbbc.
                ....c55555ddd5bdddddbbc.
                .cccc55555ddd55cd55dddc.
                .ccc5555555dd55cd555d55c
                ..cc55cc5555db55cd5d555c
                ...c55c55555db55cbd5555c
                ...c55c55b555b55cbc555c.
                ...c55555bbb5dbbbbc55c..
                ...c55555513b5cccccc....
                ....c555553335ccc55c....
                ....c555d5b335c.c5c.....
                .....c5555b55c..cc......
                ......c555ccc...........
                .......ccc..............
                `)
            fightext_character.setStImage(player2, fightext_character.stimgKind.Stand, img`
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb555555ff155555c
                ......cb55555555ff55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb13bbc.
                ...cccd55ddddd555b3335c.
                .....bdddddddddd55b335c.
                ..cccdddddb55bbddd5555c.
                ..cccdddddb555bbbbcccc..
                ...ccddddddb5555cbcdc...
                ccccbdddddd5cb55cbcc....
                cddddddddd5555ccbbc.....
                .cddddddbdd555bbbcc.....
                ..ccdddbbbdd55cbcdc.....
                ....ccbbcbddddccdddcc...
                ......cccdd555dcccccc...
                ........cccccccc........
                `)
            fightext_character.setStImage(player2, fightext_character.stimgKind.Quickst, img`
                ........................
                ............cc..........
                ............ccc.........
                ........ccc.ccccccc.....
                ........ccccc555555cc...
                ........ccb5555555555c..
                .....ccc.b55555ff15555c.
                .....cccb5555555ff55555c
                ......cb555555555555d55c
                ....c.b555555555bb55555c
                ....ccb555ddd5555b13bbc.
                ....ccd55ddddd555b3335c.
                .....cdd5ddddddd55b335c.
                ...c.bddddb555bbbd555c..
                ...ccdddddbb55555bccc...
                ...ccdddddddcc555bcc....
                .ccccdddddddddcccbcccc..
                .cdcdddddddd55dbbbc55c..
                .cdddddddddd555dccc5c...
                .cbddddbbbbdd5d555cc....
                ..cbdddbbbbbdd5555......
                ...cccbbbbbbd5555c......
                .....cccccccc555c.......
                .............ccc........
                `)
            fightext_character.setWalkImage(player2, fightext_character.aniKind.Hurt, [img`
                .........ccc............
                .........cccccccc.......
                ......cc..cc55555cc.....
                ......cccc555555555c....
                ......ccb55555555555c...
                ...cc..b5555bcc555555c..
                ...cccb55555555c55d55c..
                ....ccb55555d5c555555c..
                .....b55555d5555d5555c..
                ..cc.b555ddd55555bbbbc..
                ..cccd55ddddd5555d555c..
                ...ccdd5dbdddbbbd555c...
                ....bdddb555bbbbbccc....
                ..cccdddb555cbbbbbbc....
                ...ccddddb555cbbbbbbc...
                ....cdddddb555cbbbbbc...
                ...ccddddddb55cbbbbbcc..
                ..ccbddddd55bcbbbbbbcc..
                ccdddddddd5555bbbbbbc...
                cdddddddbdd555bbbbbc....
                .ccddddbbbdd55cbbccc....
                ...cccbbcbddddccdddcc...
                ......cccdd555dcccccc...
                ........cccccccc........
                `,img`
                ........ccc.............
                ........cccccccc........
                .....cc..cc55555cc......
                .....cccc555555555c.....
                .....ccb55555555555c....
                ...cc.b5555bcc555555c...
                ...ccb55555555c55d55c...
                ....cb5555dd5c555555c...
                .....5555dd5555d5555c...
                ..cc.555dd555555dbbbc...
                ..ccc55ddd555555d555c...
                ...ccd5dbdd5555d555c....
                ....bdddb555bbbbbccc....
                ..cccdddb555cbbbbbbbc...
                ...ccddddb555cbbbbbbbc..
                ....cdddddb555cbbbbbbc..
                ...ccddddddb55cbbbbbbcc.
                ...cbddddd55bcbbbbbbbcc.
                ..cbdddddd5555bbbbbbbc..
                .cddddddbdd555bbbbbbc...
                cddddddbbbdd55cbbccc....
                ccccccbbcbddddccdddcc...
                ......cccdd555dcccccc...
                ........cccccccc........
                `,img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b555555555c555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd5bbbb335c.
                ...ccbdddddddd5bbbb335c.
                .ccccddddddddd55bbb335c.
                cdcccdddddb55bb5bb3322c.
                cddbddddddb555bb5b32352.
                cddddddddddb5555b53325c2
                ccddddddbd55bb55c55552..
                .ccddddbbbdd55cccbccc...
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `,img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b555555555c555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd5bbbb335c.
                ...ccbdddddddd5bbbb335c.
                .ccccddddddddd55bb3325c.
                cdcccdddddb55bb55b32322.
                cddbddddddb555bb553325c2
                cddddddddddb5555b55552..
                ccddddddbd55bb55cbccc...
                .ccddddbbbdd55ccbbc.....
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `,img`
                ........................
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb55555bcc555555c
                ......cb555555555c55d55c
                ......b555555555c555555c
                ...cc.b555dd5555bb1bbbc.
                ....ccd55ddddd55bbb335c.
                ...ccbddddddddd5bb3335c.
                .ccccdddddddddd55b3335c.
                cdcccdddddb55bbd552325c.
                cddbddddddb555bb552552..
                cddddddddddb5555b2cc2...
                ccddddddbd55bb55cbc.2...
                .ccddddbbbdd55ccbdc.....
                ...ccbbbcbddddccdddc....
                .....ccccdd555dccccc....
                ........cccccccc........
                `])
            fightext_character.setWalkImage(player2, fightext_character.aniKind.Walk, [img`
                ........................
                ........................
                ...........cc...........
                ...........cccc.........
                .......cc...ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb555555ff155555c
                .....ccb55555555ff55d55c
                ......b5555555555555555c
                ...c..b555d55555bb13bbc.
                ...cccd55ddddd55bb3335c.
                ....cbdddddddddd55b335c.
                ..cccdddddb55bdddd5555c.
                ..cccdddddb555bbbbcccc..
                ...ccddddddb5555cbcdc...
                ccccbdddddddcb55cbcc....
                cddddddddd55dbccbbc.....
                cbdddddddd555dbbbcc.....
                .ccbdddbbdd555bbcdbcc...
                ...cccbbbbdd55ccdddbc...
                ......cccbdddbccccccc...
                ........cdd555dc........
                `,img`
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb555555ff155555c
                ......cb55555555ff55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb13bbc.
                ...cccd55ddddd555b3335c.
                .....bdddddddddd55b335c.
                ..cccdddddb55bbddd5555c.
                ..cccdddddb555bbbbcccc..
                ...ccddddddb5555cbcdc...
                ccccbdddddd5cb55cbcc....
                cddddddddd5555ccbbc.....
                .cddddddbdd555bbbcc.....
                ..ccdddbbbdd55cbcdc.....
                ....ccbbcbddddccdddcc...
                ......cccdd555dcccccc...
                ........cccccccc........
                `,img`
                ........................
                ............cc..........
                ............ccc.........
                ........ccc.ccccccc.....
                ........ccccc555555cc...
                ........ccb5555555555c..
                .....ccc.b55555ff15555c.
                .....cccb5555555ff55555c
                ......cb555555555555d55c
                ....c.b555555555bb55555c
                ....ccb555ddd5555b13bbc.
                ....ccd55ddddd555b3335c.
                .....cdd5ddddddd55b335c.
                ...c.bddddb555bbbd555c..
                ...ccdddddbb55555bccc...
                ...ccdddddddcc555bcc....
                ...ccddddddddbcccbcccc..
                .ccbddddddd55dbbbbc55c..
                ccddddddddd555dbbcc5c...
                cddddddbbbdd555bbccc....
                .ccddddbbbbdd55bcc......
                ...cccbbbbbdddbcddcc....
                .....cccccdd555dcccc....
                ..........cccccc........
                `,img`
                ........................
                ............cc..........
                ............ccc.........
                ........ccc.ccccccc.....
                ........ccccc555555cc...
                ........ccb5555555555c..
                .....ccc.b55555ff15555c.
                .....cccb5555555ff55555c
                ......cb555555555555d55c
                ....c.b555555555bb55555c
                ....ccb555ddd5555b13bbc.
                ....ccd55ddddd555b3335c.
                .....cdd5ddddddd55b335c.
                ...c.bddddb555bbbd555c..
                ...ccdddddbb55555bccc...
                ...ccdddddddcc555bcc....
                .ccccdddddddddcccbcccc..
                .cdcdddddddd55dbbbc55c..
                .cdddddddddd555dccc5c...
                .cbddddbbbbdd5d555cc....
                ..cbdddbbbbbdd5555......
                ...cccbbbbbbd5555c......
                .....cccccccc555c.......
                .............ccc........
                `,img`
                ........................
                ............cc..........
                ............ccc.........
                ........ccc.ccccccc.....
                ........ccccc555555cc...
                ........ccb5555555555c..
                .....ccc.b55555ff15555c.
                .....cccb5555555ff55555c
                ......cb555555555555d55c
                ....c.b555555555bb55555c
                ....ccb555ddd5555b13bbc.
                ....ccd55ddddd555b3335c.
                .....cdd5ddddddd55b335c.
                ...c.bddddb555bbbd555c..
                ...ccdddddb555555bccc...
                ..cccddddddcc5555bcc....
                .cdccddddddddbcccbcccc..
                .cddbdddddddddbbbbc55c..
                .cdddddddddd55dbbbc5c...
                .cbddddbbbbd55ddbccc....
                ..cbdddbbbbd555dccc.....
                ...cccbbbbbbddd555c.....
                .....ccccccbd55555c.....
                ...........cc5555c......
                `,img`
                ........................
                ............cc..........
                ............ccc.........
                ........cc..ccccccc.....
                ........ccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb555555ff155555c
                ......cb55555555ff55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb13bbc.
                ...cccd55ddddd555b3335c.
                ....ccdd5ddddddd55b335c.
                .....bddddb55bdddd5555c.
                ..cccdddddb55bbbbbcccc..
                .ccccddddddb5555cbcccc..
                .cdccdddddddc555cbc55c..
                .cdddddddddddcccbbc5c...
                .cbddddddd55dbbbbccc....
                .ccbdddddd555dbbbcbc....
                ..cccddbbbd555bbccc.....
                ....ccbbbbbd555cc.......
                ......ccccbddddbc.......
                ..........cd5555dc......
                `], 100)
            fightext_character.setAbility(player2, fightext_character.abilityKind.def, 0.4)
        })

        let 替身巨龙 = "替身巨龙"
        let 火球 = "火球"
        let 尾焰 = "尾焰"
        let projectile: fightext_projectile.WaveSprite = null
        let skill2 = null
        fightext_skill.skillSet("恶龙", function (player2) {
            fightext_skill.setSkill(player2, fightext_skill.SkillKind.B8, 8, function (tempVar, player2) {
                multishot(fightext_skill.newPosture(player2, img`
                    ........................................
                    ........................................
                    ........................................
                    ..................ccc...................
                    ..................cccc..................
                    ..............ccc..ccccccc..............
                    ..............cccccc555555cc............
                    ...............ccb5555555555c...........
                    ............cc..b555555555555c..........
                    ............cccb55555bcc555555c.........
                    .............cb555555555c55d55c.........
                    .............b5555555555555555c.........
                    ..........cc.b555dd5555bb1bbbc..........
                    ...........ccd55ddddd5bbbb335c..........
                    ..........ccbdddddddd5bbbb335c..........
                    ........ccccddddddddd55bbb335c..........
                    .......cdcccdddddb55bb5bb3335c..........
                    .......cddbddddddb555bb5b3335c..........
                    .......cddddddddddb5555b53335c..........
                    .......ccddddddbd55bb55c5555c...........
                    ........ccddddbbbdd55cccbccc............
                    ..........ccbbbcbddddccdddc.............
                    ............ccccdd555dccccc.............
                    ...............cccccccc.................
                    `, 1.1, img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `), 180, 3, 0.3, 0, 火球)
            })
            fightext_skill.setSkill(player2, fightext_skill.SkillKind.A8, 5, function (tempVar, player2) {
                multishot(fightext_skill.newPosture(player2, img`
                    ........................................
                    ........................................
                    ........................................
                    ..................ccc...................
                    ..................cccc..................
                    ..............ccc..ccccccc..............
                    ..............cccccc555555cc............
                    ...............ccb5555555555c...........
                    ............cc..b555555555555c..........
                    ............cccb55555bcc555555c.........
                    .............cb555555555c55d55c.........
                    .............b5555555555555555c.........
                    ..........cc.b555dd5555bb1bbbc..........
                    ...........ccd55ddddd5bbbb335c..........
                    ..........ccbdddddddd5bbbb335c..........
                    ........ccccddddddddd55bbb335c..........
                    .......cdcccdddddb55bb5bb3335c..........
                    .......cddbddddddb555bb5b3335c..........
                    .......cddddddddddb5555b53335c..........
                    .......ccddddddbd55bb55c5555c...........
                    ........ccddddbbbdd55cccbccc............
                    ..........ccbbbcbddddccdddc.............
                    ............ccccdd555dccccc.............
                    ...............cccccccc.................
                    `, 0.3, img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `), 190, 3, 0, -10, 火球)
            })
            fightext_skill.setSkill(player2, fightext_skill.SkillKind.B10, 60, function (tempVar, player2) {
                fightext_character.atkAction(player2, fightext_character.atkKind.RushAtkB, 1)
                fightext_skill.shoot2(player2, 替身巨龙, player2.x, player2.y - 25, 180, 0, 30)
            })
            fightext_skill.setSkill(player2, fightext_skill.SkillKind.B9, 15, function (tempVar, player2) {
                projectile = fightext_skill.newPosture(player2, img`
                    ........................................
                    ........................................
                    ........................................
                    ..................ccc...................
                    ..................cccc..................
                    ..............ccc..ccccccc..............
                    ..............cccccc555555cc............
                    ...............ccb5555555555c...........
                    ............cc..b555555555555c..........
                    ............cccb55555bcc555555c.........
                    .............cb555555555c55d55c.........
                    .............b5555555555555555c.........
                    ..........cc.b555dd5555bb1bbbc..........
                    ...........ccd55ddddd5bbbb335c..........
                    ..........ccbdddddddd5bbbb335c..........
                    ........ccccddddddddd55bbb335c..........
                    .......cdcccdddddb55bb5bb3335c..........
                    .......cddbddddddb555bb5b3335c..........
                    .......cddddddddddb5555b53335c..........
                    .......ccddddddbd55bb55c5555c...........
                    ........ccddddbbbdd55cccbccc............
                    ..........ccbbbcbddddccdddc.............
                    ............ccccdd555dccccc.............
                    ...............cccccccc.................
                    `, 1.1, img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `)
                fightext_skill.shoot2(player2, "火焰弹", player2.x, player2.y + 3, 180, 100, 10)
            })
            fightext_skill.setSkill(player2, fightext_skill.SkillKind.A9, 15, function (tempVar, player2) {
                multishot(fightext_skill.newPosture(player2, img`
                    ........................................
                    ........................................
                    ........................................
                    ..................ccc...................
                    ..................cccc..................
                    ..............ccc..ccccccc..............
                    ..............cccccc555555cc............
                    ...............ccb5555555555c...........
                    ............cc..b555555555555c..........
                    ............cccb55555bcc555555c.........
                    .............cb555555555c55d55c.........
                    .............b5555555555555555c.........
                    ..........cc.b555dd5555bb1bbbc..........
                    ...........ccd55ddddd5bbbb335c..........
                    ..........ccbdddddddd5bbbb335c..........
                    ........ccccddddddddd55bbb335c..........
                    .......cdcccdddddb55bb5bb3335c..........
                    .......cddbddddddb555bb5b3335c..........
                    .......cddddddddddb5555b53335c..........
                    .......ccddddddbd55bb55c5555c...........
                    ........ccddddbbbdd55cccbccc............
                    ..........ccbbbcbddddccdddc.............
                    ............ccccdd555dccccc.............
                    ...............cccccccc.................
                    `, 1.1, img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `), 190, 6, 0.1, 0, "火焰轮")
            })
            fightext_skill.setSkill(player2, fightext_skill.SkillKind.A1, 25, function (tempVar, player2) {
                projectile = fightext_skill.newPosture(player2, img`
                    ........................................
                    ........................................
                    ........................................
                    ..................ccc...................
                    ..................cccc..................
                    ..............ccc..ccccccc..............
                    ..............cccccc555555cc............
                    ...............ccb5555555555c...........
                    ............cc..b555555555555c..........
                    ............cccb55555bcc555555c.........
                    .............cb555555555c55d55c.........
                    .............b5555555555555555c.........
                    ..........cc.b555dd5555bb1bbbc..........
                    ...........ccd55ddddd5bbbb335c..........
                    ..........ccbdddddddd5bbbb335c..........
                    ........ccccddddddddd55bbb335c..........
                    .......cdcccdddddb55bb5bb3335c..........
                    .......cddbddddddb555bb5b3335c..........
                    .......cddddddddddb5555b53335c..........
                    .......ccddddddbd55bb55c5555c...........
                    ........ccddddbbbdd55cccbccc............
                    ..........ccbbbcbddddccdddc.............
                    ............ccccdd555dccccc.............
                    ...............cccccccc.................
                    `, 0.3, img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `)
                fightext_skill.shoot2(player2, "星星之火", player2.x, player2.y, 180, 0, 10)
            })
        })

    }    

}